// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace BeginCollectionItem.Mvc3Demo.Controllers {
    public partial class DemoController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public DemoController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected DemoController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }


        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public DemoController Actions { get { return MVC.Demo; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Demo";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Demo";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string Order = "Order";
            public readonly string OrderItem = "OrderItem";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants {
            public const string Order = "Order";
            public const string OrderItem = "OrderItem";
        }


        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string _OrderItem = "~/Views/Demo/_OrderItem.cshtml";
            public readonly string Order = "~/Views/Demo/Order.cshtml";
            public readonly string OrderSubmitted = "~/Views/Demo/OrderSubmitted.cshtml";
            static readonly _EditorTemplates s_EditorTemplates = new _EditorTemplates();
            public _EditorTemplates EditorTemplates { get { return s_EditorTemplates; } }
            public partial class _EditorTemplates{
                public readonly string OrderItemModel = "OrderItemModel";
            }
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_DemoController: BeginCollectionItem.Mvc3Demo.Controllers.DemoController {
        public T4MVC_DemoController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ViewResult Order() {
            var callInfo = new T4MVC_ViewResult(Area, Name, ActionNames.Order);
            return callInfo;
        }

        public override System.Web.Mvc.ViewResult Order(BeginCollectionItem.Mvc3Demo.Models.OrderModel model) {
            var callInfo = new T4MVC_ViewResult(Area, Name, ActionNames.Order);
            callInfo.RouteValueDictionary.Add("model", model);
            return callInfo;
        }

        public override System.Web.Mvc.PartialViewResult OrderItem() {
            var callInfo = new T4MVC_PartialViewResult(Area, Name, ActionNames.OrderItem);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
